import sys
import os
import pandas as pd
from analyzer import BikeShareSystem
from algorithms import benchmark_sort
from numerical import analyze_durations
from visualization import plot_top_stations, plot_duration_histogram
from pricing import TripFareCalculator, RegularPricing, SubscriberPricing
from utils import format_currency, ensure_dir

def save_and_report(system, stats, sorted_counts):
    print("\n📂 Generating Full Business Insights Report...")
    try:
        df = pd.DataFrame([vars(t) for t in system.trips])
        
        time_col = next((col for col in df.columns if 'time' in col.lower() or 'date' in col.lower()), None)

        report_path = 'output/summary_report.txt'
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("="*55 + "\n")
            f.write("       CITY BIKE SYSTEM - AUTOMATED ANALYTICS      \n")
            f.write("="*55 + "\n\n")

            f.write(f"[Q1] Total Trips: {len(df)}\n")
            f.write(f"[Q1] Avg Duration: {stats.get('mean', 0):.2f} min\n\n")

            f.write("--- [Q2] Top 5 Popular Start Stations ---\n")
            for i, (name, count) in enumerate(list(sorted_counts.items())[:5], 1):
                f.write(f"{i}. {name}: {count} trips\n")

            if time_col:
                df[time_col] = pd.to_datetime(df[time_col])
                peak_hour = df[time_col].dt.hour.mode()[0]
                peak_day = df[time_col].dt.day_name().mode()[0]
                
                f.write(f"\n[Q3] Peak Hour (Calculated): {peak_hour}:00\n")
                f.write(f"[Q4] Busiest Day (Calculated): {peak_day}\n")
            else:
                f.write("\n[Q3] Peak Hour: Data column not found\n")
                f.write("[Q4] Busiest Day: Data column not found\n")

            user_col = next((col for col in df.columns if 'user' in col.lower() or 'id' in col.lower()), None)
            if user_col:
                top_users = df[user_col].value_counts().head(3)
                f.write("\n--- [Q5] Top Active Users ---\n")
                for uid, count in top_users.items():
                    f.write(f"- {uid}: {count} trips\n")

            f.write("\n" + "="*55 + "\n")
            f.write("Generated by: Yasser Nourallah - Data Analytics Suite\n")

        print(f"✅ Report generated successfully: {report_path}")

    except Exception as e:
        print(f"⚠️ Technical Error during calculation: {e}")

def main_menu():
    print("\n" + "="*30)
    print("   CITY BIKE ANALYSIS SYSTEM   ")
    print("="*30)
    print("1. View Global Statistics & Pricing")
    print("2. Plot Trip Distributions")
    print("3. Analyze Top 5 Stations")
    print("4. Save & Exit")
    return input("Select an option (1-4): ")

def main():
    ensure_dir('output/figures')
    system = BikeShareSystem()
    
    try:
        print("🚀 Loading system data...")
        system.load_data('data/stations.csv', 'data/trips.csv')
        
        print("⚖️ Sorting trips using Merge Sort...")
        system.trips = benchmark_sort(system.trips, key_func=lambda x: x.duration, label="Merge Sort")

        while True:
            choice = main_menu()
            
            if choice == '1':
                stats = analyze_durations(system.trips)
                print("\n📊 --- Global Statistics ---")
                for key, value in stats.items():
                    print(f"{key.capitalize()}: {value:.2f} min")

                reg_calc = TripFareCalculator(RegularPricing())
                sub_calc = TripFareCalculator(SubscriberPricing())
                avg_dur = stats.get('mean', 0)
                print(f"\n💰 Regular Fare (Avg):    {format_currency(reg_calc.calculate_fare(avg_dur))}")
                print(f"💰 Subscriber Fare (Avg): {format_currency(sub_calc.calculate_fare(avg_dur))}")

            elif choice == '2':
                durations = [t.duration for t in system.trips]
                plot_duration_histogram(durations)
                print(f"✅ Chart saved to: output/figures/duration_dist.png")

            elif choice == '3':
                counts = {}
                for t in system.trips:
                    station_name = system.stations[t.start_id].name if t.start_id in system.stations else "Unknown"
                    counts[station_name] = counts.get(station_name, 0) + 1
                sorted_counts = dict(sorted(counts.items(), key=lambda item: item[1], reverse=True))
                plot_top_stations(sorted_counts)
                print(f"✅ Chart saved to: output/figures/top_stations.png")

            elif choice == '4':
                final_stats = analyze_durations(system.trips)
                counts = {}
                for t in system.trips:
                    station_name = system.stations[t.start_id].name if t.start_id in system.stations else "Unknown"
                    counts[station_name] = counts.get(station_name, 0) + 1
                final_sorted_counts = dict(sorted(counts.items(), key=lambda item: item[1], reverse=True))
                
                save_and_report(system, final_stats, final_sorted_counts)
                print("Exiting system. Goodbye!")
                break
            else:
                print("❌ Invalid choice. Please enter 1-4.")

    except Exception as e:
        print(f"❌ Critical Error: {e}")

if __name__ == "__main__":
    main()
